SPOOL formato_autores.lst;

SET PAGESIZE 50;
SET LINESIZE 80; -- Queda mal pero no importa
SET HEADING ON;
SET UNDERLINE '-';
SET FEEDBACK OFF;

TTITLE CENTER 'INFORME DE AUTORES' SKIP 1 CENTER 'CON FECHAS NO CONOCIDAS';
BTITLE CENTER 'SERVICIO  DE BIBLIOTECAS';

COLUMN Apellido FORMAT A12;
COLUMN Nacionalidad HEADING 'NACION' FORMAT A15;
COLUMN Ano_Nac HEADING 'ANO NACIMIENTO' FORMAT 9999;
COLUMN Ano_Fall HEADING 'ANO MUERTE' FORMAT 9999;

SELECT A.Nombre, A.Apellido, N.Nombre AS Nacionalidad, 
NVL(TO_CHAR(A.Ano_Nac), '???') AS "ANO NACIMIENTO",
NVL(TO_CHAR(A.Ano_Fall), '???') AS "ANO MUERTE"
FROM AUTOR A
JOIN NACIONALIDAD N ON A.Cod_Nacion = N.Codigo
WHERE A.Ano_Nac IS NULL OR A.Ano_Fall IS NULL
ORDER BY A.Apellido;

SPOOL OFF;

TTITLE OFF;
BTITLE OFF;